import type { Metadata } from "next";
import { Bricolage_Grotesque, Inter, Syne } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/nav/navigation";
import Grid from "@/components/nav/grid";

const bricolageGrotesque = Bricolage_Grotesque({ 
	subsets: ["latin"], 
	variable: "--font-large", 
	fallback: ['sans-serif']
});
const inter = Inter({ 
	subsets: ["latin"], 
	variable: "--font-body", 
	fallback: ['sans-serif']
});
const syne = Syne({ 
	subsets: ["latin"], 
	variable: "--font-titles", 
	fallback: ['sans-serif']
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body suppressHydrationWarning={true} className={`${bricolageGrotesque.variable} ${inter.variable} ${syne.variable}`}>
				{children}
				<Navigation />
				{/* <Grid /> */}
			</body>
		</html>
	);
}
